In [26]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

%matplotlib inline


plt.rcParams['figure.figsize'] = (6, 4)
plt.style.use('ggplot')
%config InlineBackend.figure_formats = {'png', 'retina'}

In [27]:
anime = pd.read_csv('anime.csv')
anime.head()

anime_id                              name  \
0     32281                    Kimi no Na wa.   
1      5114  Fullmetal Alchemist: Brotherhood   
2     28977                          Gintama°   
3      9253                       Steins;Gate   
4      9969                     Gintama&#039;   

                                               genre   type episodes  rating  \
0               Drama, Romance, School, Supernatural  Movie        1    9.37   
1  Action, Adventure, Drama, Fantasy, Magic, Mili...     TV       64    9.26   
2  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.25   
3                                   Sci-Fi, Thriller     TV       24    9.17   
4  Action, Comedy, Historical, Parody, Samurai, S...     TV       51    9.16   

   members  
0   200630  
1   793665  
2   114262  
3   673572  
4   151266

In [28]:
user = pd.read_csv('rating.csv')
user.sample(10)

user_id  anime_id  rating
6803043    62984      6213       8
3798106    35490     16706      10
7211790    67264       318       7
1841326    17842     12189       9
6343647    58912       101      10
187328      1873      3731       7
7112040    66343     12467       4
2076064    20106      5460       8
3149882    29111      5507       7
5591828    52504       710       8

In [29]:
print("Shape of anime dataset {}".format(anime.shape))

Shape of anime dataset (12294, 7)


In [30]:
print("Shape of user dataset {}".format(user.shape))

Shape of user dataset (7813737, 3)


In [17]:
user[user['user_id'] == 1].rating.mean()

-0.7124183006535948

In [18]:
user[user['user_id'] == 7].rating.mean()

7.387755102040816

In [31]:
Mean_Rate = user.groupby(['user_id']).mean().reset_index()
print(Mean_Rate.head(10))
print("Shape of this datset is {}".format(Mean_Rate.shape))

   user_id      anime_id    rating
0        1  12888.483660 -0.712418
1        2  13459.000000  2.666667
2        3  13352.744681  7.382979
3        4  10135.403846 -1.000000
4        5  11023.301927  4.263383
5        6   7752.135135 -1.000000
6        7  15824.320700  7.387755
7        8   8699.166667  8.333333
8        9   1887.000000  8.000000
9       10   8579.875000  2.875000
Shape of this datset is (73515, 3)


In [37]:
Mean_Rate['mean_rating'] = Mean_Rate['rating']
print(Mean_Rate.head())

   user_id      anime_id    rating  mean_rating
0        1  12888.483660 -0.712418    -0.712418
1        2  13459.000000  2.666667     2.666667
2        3  13352.744681  7.382979     7.382979
3        4  10135.403846 -1.000000    -1.000000
4        5  11023.301927  4.263383     4.263383


In [38]:
Mean_Rate.drop(['anime_id','rating'], axis=1,inplace=True)
print(Mean_Rate.head())

   user_id  mean_rating
0        1    -0.712418
1        2     2.666667
2        3     7.382979
3        4    -1.000000
4        5     4.263383


In [39]:
user = pd.merge(user, Mean_Rate, on=['user_id', 'user_id'])
print(user.head())

   user_id  anime_id  rating  mean_rating
0        1        20      -1    -0.712418
1        1        24      -1    -0.712418
2        1        79      -1    -0.712418
3        1       226      -1    -0.712418
4        1       241      -1    -0.712418


In [43]:
#If user rating is less then mean_rating we drop that column as we are looking which anime is liked by the user
user = user.drop(user[user.rating < user.mean_rating].index)

In [44]:
print(user[user['user_id'] == 1])

     user_id  anime_id  rating  mean_rating
47         1      8074      10    -0.712418
81         1     11617      10    -0.712418
83         1     11757      10    -0.712418
101        1     15451      10    -0.712418


In [45]:
print(user[user['user_id'] == 7])

      user_id  anime_id  rating  mean_rating
807         7        30      10     7.387755
808         7        31       9     7.387755
809         7        32       9     7.387755
811         7        64       8     7.387755
813         7       111       8     7.387755
...       ...       ...     ...          ...
1121        7     31149       8     7.387755
1130        7     31704       8     7.387755
1131        7     31716       8     7.387755
1140        7     32093       8     7.387755
1147        7     33091       8     7.387755

[164 rows x 4 columns]


In [46]:
print("Updated shape of the user is now {}".format(user.shape))

Updated shape of the user is now (4262566, 4)


In [49]:
unique_user = np.unique(user['user_id'])
print(unique_user)
print(len(unique_user))

[    1     2     3 ... 73514 73515 73516]
73515


In [54]:
user = user.rename({'rating':'userRating'}, axis='columns')
print(user.head())

     user_id  anime_id  userRating  mean_rating
47         1      8074          10    -0.712418
81         1     11617          10    -0.712418
83         1     11757          10    -0.712418
101        1     15451          10    -0.712418
153        2     11771          10     2.666667


In [56]:
mergedata = pd.merge(anime, user, on=['anime_id','anime_id'])
print(mergedata.head())

   anime_id            name                                 genre   type  \
0     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
1     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
2     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
3     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   
4     32281  Kimi no Na wa.  Drama, Romance, School, Supernatural  Movie   

  episodes  rating  members  user_id  userRating  mean_rating  
0        1    9.37   200630      152          10     7.699301  
1        1    9.37   200630      244          10     8.729242  
2        1    9.37   200630      271          10     7.372287  
3        1    9.37   200630      322          10     8.356322  
4        1    9.37   200630      398          10    -0.832298  


In [60]:
unique_user = np.unique(mergedata['user_id'])
print(unique_user)
print(len(unique_user))

[    1     2     3 ... 73514 73515 73516]
73515


In [31]:
unique_anime = np.unique(mergedata['anime_id'])
print(unique_anime)
print(len(unique_anime))
unique_anime = np.unique(mergedata['name'])
print(unique_anime)
print(len(unique_anime))

[    1     5     6 ... 34475 34476 34519]
10756
['&quot;0&quot;'
 '&quot;Aesop&quot; no Ohanashi yori: Ushi to Kaeru, Yokubatta Inu'
 '&quot;Bungaku Shoujo&quot; Kyou no Oyatsu: Hatsukoi' ...
 'xxxHOLiC Movie: Manatsu no Yoru no Yume' 'xxxHOLiC Rou'
 'xxxHOLiC Shunmuki']
10755


In [ ]:
#Now we are going to create a crosstable of 'user_id' and 'name' using pandas.crosstab
#here we use 'user_id' as row or index and 'name' as column
user_anime = pd.crosstab(mergedata['user_id'], mergedata['name'])
user_anime.sample(5)